### ISSUE TITLE
Python 3.5/3.6

### ISSUE THREAD

**Issue by TheodoreGalanos** [Digital-Structures/ghpythonremote#1]
Hi, 

First of all thanks for this amazing plugin!

I was wondering if you plan support for python 3 version anytime soon? It would open a lot of possibilities to certain areas.

Kind regards,
Theodore.

**Comment by pilcru** [comment]
Unfortunately, no.

IronPython stopped development at 2.7.7, the version shipping with Rhino is currently 2.7.5, and that's the only interpreter that will let you run `import Rhino`. So anything that works with the Rhino Python libraries needs to be Python 2 or be able to translate on the fly between Python 2 and 3. RPyC, the remote computing library behind GhPythonRemote, does not and [will not support this](http://rpyc.readthedocs.io/en/latest/install.html#cross-interpreter-compatibility).

Things do not look much better with Rhino 6, since it is still using IronPython to interface with their .NET framework code.

If you absolutely need to call out to Python 3 from GH, you can have a look at [GH CPython](https://github.com/MahmoudAbdelRahman/GH_CPython), but then you cannot import Rhino libraries in these scripts.

Out of curiosity, what libraries did you want to use that are Python 3 only?

**Comment by TheodoreGalanos** [comment]
Hi Pierre,

Thanks for the update, sounds good.

The main thing I am testing currently is tensorflow, which is only python3 for Windows.

In my case, doing machine learning, I don't really need (at least not yet) many Rhino specific libraries since I'm not currently developing components but only importing python libraries after all the GH definition has done its work in order to train models on my data.

I can still do vanilla ML with this and it can still be used to create ML components with scikit-learn for example. So it's cool. I won't be doing much DL inside GH anyways!

Kind regards,
Theodore.

**Comment by gonzalocasas** [comment]
+1 to this, despite being a "Not a chance" closed issue.

Right now, the library that I would like to use on python 3 is the async/await support. I know there's a backport for 2.7, but python 2.x is a dead end as it's officially [End of Life](http://legacy.python.org/dev/peps/pep-0373/) and won't be supported anymore after 2020. It feels so wrong to not be able to use python 3 in 2017 😢
