### ISSUE TITLE
Using Numba

### ISSUE THREAD

**Issue by op-rt** [Digital-Structures/ghpythonremote#31]
Dear @pilcru,

First let me thank you for this wonderful tool that is GHPythonRemote.

I would like to know if it is possible to use Numba with it and if so, how.
Importing it doesn't seem to be an issue but adding a `@jit` decorator to a function returns an error.

Example test:

```
nb = scriptcontext.sticky['numba']
jit = nb.jit

@jit
def f(x, y):
    return x + y

f(24, 167)
```

Returned error:

```
Runtime error (Exception): NotImplementedError

Traceback:
  line 58, in script
  line 102, in value, "C:\Users\solub\AppData\Roaming\McNeel\Rhinoceros\6.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\async_.py"
  line 458, in sync_request, "C:\Users\solub\AppData\Roaming\McNeel\Rhinoceros\6.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\protocol.py"
  line 76, in syncreq, "C:\Users\solub\AppData\Roaming\McNeel\Rhinoceros\6.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\netref.py"
  line 247, in __call__, "C:\Users\solub\AppData\Roaming\McNeel\Rhinoceros\6.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\netref.py"
```

**Comment by pilcru** [comment]
Hi @solub,

Thank you for trying the plugin! Numba is only half compatible with GHPythonRemote, you can import modules that use numba but cannot import numba and call `jit` on IronPyton code.

While it's possible to use numba on the CPython side of the connection, it's not possible to cross the interface and use it on functions defined on the IronPython side. The problem is that numba needs to access the bytecode of the function to be JITed, and GHPythonRemote does not know how to transfer that. I don't even know of a way to access that information on IronPython like on CPython (I initially tried to transfer the function to the CPython side with a [utility from RPyC](https://rpyc.readthedocs.io/en/latest/api/utils_classic.html#rpyc.utils.classic.teleport_function), but that's trying to access function properties that are not defined in the IronPython implementation).

So the best you can do is code everything that needs to use numba in a separate CPython module, and add this module to the list of modules to import through GHPythonRemote. The module needs to be importable by your CPython installation (rhinoremote virtual environment, probably), that is be in its python path. I find the easiest way to achieve that is to create a package with a simple `setup.py` file, and use an editable install: `pip install -e .` (run this from the folder containing the `setup.py` file, with `rhinoremote` activated).

There is an example project layout with a simple setup.py [here](https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/quickstart.html).

**Comment by op-rt** [comment]
Thank you so much for the kind reply and the comprehensive explanation. This is very helpful.
