### ISSUE TITLE
Python 3+ support

### ISSUE THREAD

**Issue by Sonderwoods** [Digital-Structures/ghpythonremote#33]
Hi guys,

is there a workaround in order to get python 3 support?

I'm really looking a way to connect this to tensorflow and that only runs on python 3+.

I did try a workflow with gh_cpython, that worked well with tensorflow, but then I'm missing out on sc.sticky etc.

**Comment by pilcru** [comment]
No, the answer is still the same as in #1. As long as Rhino runs IronPython 2, it will not be possible to use this plugin to interface with Python 3. The reason is that it's not possible to translate python 2 to python 3 code on the fly.

For Tensorflow, one workaround is to run it on a Linux machine under python 2, and use that as a remote interpreter in GH Python Remote. But it's a lot of hacking for one specific package, and too many configuration possibilities to deal with in the time I have. Happy to look at a PR if you want to try that :)
