### ISSUE TITLE
Problem running example files

### ISSUE THREAD

**Issue by anders-smith** [Digital-Structures/ghpythonremote#46]
Running in a 2.7 environment ( conda://rhinoremote ) as directed in the guide and from a fresh anaconda3 install, I'm having problems running the GH to python remote example.

I have the following modules:
```
import scriptcontext as sc
scipy = sc.sticky['scipy']
numpy.linalg = sc.sticky['numpy.linalg']
numpy = sc.sticky['numpy']
```

I get the following error:
```
0. Runtime error (KeyNotFoundException): numpy
Traceback: line 3, in script
```
Any help/guidance would be much appreciated

thanks
anders

**Comment by pilcru** [comment]
Seems to be working fine here, this may be something as simple as making sure that you turn and keep on the remote Python. In the example files the "run" input of the GH Python Remote component is connected to a boolean toggle; this toggle needs to be turned on and stay on for as long as you want to use the remote Python environment.

Also, which example file are you running? I don't think the code you pasted is in them. Your code also fails on an error non-related to GH PYthon Remote and that is not the error you get:
```
Runtime error (UnboundNameException): name 'numpy' is not defined

Traceback:
  line 3, in script
```
That is because line 3 needs to be after line 4 for `numpy.linalg` to make sense.

**Comment by anders-smith** [comment]
It was just me being presumptuous and expecting that Python would be automatically be started when I clicked start in Grasshopper..

Thanks

anders
