### ISSUE TITLE
"Location" is inside Docker container

### ISSUE THREAD

**Issue by rath3t** [Digital-Structures/ghpythonremote#48]
Thank you for this nice package.
I have a quite complicated situation.
I have a docker container that contains a python venv and i want to execute commands from my Rhino python code.
Is this currently possible with this library or dou you know how to achieve this?

Furthermore, Rhino 8 is adding some newer CPython functionality do you think it is feasible to enable newer Python versions here?

Thanks!

**Comment by pilcru** [comment]
Hi @rath3t, 

I do not have something available in the Grasshopper package to use a Python interpreter in a docker container. It would absolutely be possible to do, and probably not very complicating to do, however I do not have time to work on this feature now. If you want to work on this, I can help pointing you to the right places and will accept PRs.

Rhino 8 indeed has a CPython 3 engine built-in, which in my mind makes GHPythonRemote obsolete. I plan on keeping GHPythonRemote working in Rhino 8 (just for legacy purposes), where it will still be Python 2 only. This is because it will keep on using IronPython 2 on the Rhino side (Rhino is not going to update to IronPython 3), and as explained in #1 it is not possible to make Python 3 talk to Python 2 over the same data objects.

Why do you want newer versions of CPython available through GHPythonRemote when you can already run CPython 3 directly in Rhino 8?

**Comment by rath3t** [comment]
Hi @pilcru,
thanks for your response.
Basically my use case is not to have a newer python version at hand, but I have Python code that needs to be executed in linux inside my docker container. This code relies on Python 3.11. 

Thus, even for Rhino 8 I still have a use case for GHPythonRemote, since I want to execute Python code remotely.

Therefore,
maybe if I find the time i would try to implement the feature to add docker container venvs as locations to help to get my use case working in Rhino 8. Thus, if you can point me to the right places where to work, I would appreciate that.

Maybe I misunderstood a obvious thing but Im no rhino or grasshopper expert. Thanks!

**Comment by pilcru** [comment]
Maybe Hops could help you: https://developer.rhino3d.com/guides/compute/hops-component/#calling-a-cpython-server
This is becoming the standard way to call into remote procedures from Grasshopper.

**Comment by rath3t** [comment]
I played around with the Hops plugin and this is actually exactly what I want. How is this different to GHPythonRemote? Otherwise I think we can close this issue.

**Comment by pilcru** [comment]
@rath3t Sorry for the delayed reply. The difference between this and Hops is in the way the data is shared or transferred between the two Python engines:
  - GHPythonRemote shares small references to objects on the other side, and only copies data as Python primitive types, as needed when one side reads from the other side. This makes it easier to use the RhinoCommon SDK from the CPython side, but means that both sides need to share the same low level Python data format and so both be Python 2.
  - Hops copies data every time you call a Hops function, as JSON or rhino3dm format. That makes it more flexible as to what version of Python the Hops server actually runs, but also means that to get access to the RhinoCommon SDK from the Hops server you will need to run Rhino.Inside CPython. The rhino3dm package is always available from the Hops server.
